//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.14.0.4
//     Timestamp      : 18.08.2023 13:32:44
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace DialogboxExample

    Public Partial Class MainForm

        /// <summary>
        /// Required designer variable.
        /// </summary>
        Private components := Null As System.ComponentModel.IContainer
        Private label1 As System.Windows.Forms.Label
        Private groupBox1 As System.Windows.Forms.GroupBox
        Private lbBirthdate As System.Windows.Forms.Label
        Private label4 As System.Windows.Forms.Label
        Private lbUsername As System.Windows.Forms.Label
        Private label2 As System.Windows.Forms.Label
        Private bnStartDialogbox As System.Windows.Forms.Button

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Override Method Dispose(disposing As Logic) As Void  Strict

            If (disposing .AND. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
			Return
        End Method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        Private Method InitializeComponent() As Void Strict
            Self:label1 := System.Windows.Forms.Label{}
            Self:groupBox1 := System.Windows.Forms.GroupBox{}
            Self:bnStartDialogbox := System.Windows.Forms.Button{}
            Self:label2 := System.Windows.Forms.Label{}
            Self:lbUsername := System.Windows.Forms.Label{}
            Self:lbBirthdate := System.Windows.Forms.Label{}
            Self:label4 := System.Windows.Forms.Label{}
            Self:groupBox1:SuspendLayout()
            Self:SuspendLayout()
            // 
            // label1
            // 
            Self:label1:BackColor := System.Drawing.Color.FromArgb(((Int)(((Byte)(128)))), ((Int)(((Byte)(128)))), ((Int)(((Byte)(255)))))
            Self:label1:Font := System.Drawing.Font{"Arial Black", 24, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((Byte)(0))}
            Self:label1:ForeColor := System.Drawing.Color.White
            Self:label1:Location := System.Drawing.Point{30, 9}
            Self:label1:Name := "label1"
            Self:label1:Size := System.Drawing.Size{563, 53}
            Self:label1:TabIndex := 0
            Self:label1:Text := "Dialogbox example"
            // 
            // groupBox1
            // 
            Self:groupBox1:Controls:Add(Self:lbBirthdate)
            Self:groupBox1:Controls:Add(Self:label4)
            Self:groupBox1:Controls:Add(Self:lbUsername)
            Self:groupBox1:Controls:Add(Self:label2)
            Self:groupBox1:Location := System.Drawing.Point{178, 170}
            Self:groupBox1:Name := "groupBox1"
            Self:groupBox1:Size := System.Drawing.Size{264, 139}
            Self:groupBox1:TabIndex := 1
            Self:groupBox1:TabStop := False
            Self:groupBox1:Text := "Dialogbox values:"
            // 
            // bnStartDialogbox
            // 
            Self:bnStartDialogbox:Font := System.Drawing.Font{"Arial", 11.25, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((Byte)(0))}
            Self:bnStartDialogbox:Location := System.Drawing.Point{201, 77}
            Self:bnStartDialogbox:Name := "bnStartDialogbox"
            Self:bnStartDialogbox:Size := System.Drawing.Size{241, 52}
            Self:bnStartDialogbox:TabIndex := 2
            Self:bnStartDialogbox:Text := "Start dialogbox"
            Self:bnStartDialogbox:UseVisualStyleBackColor := True
            Self:bnStartDialogbox:Click += System.EventHandler{ Self, @bnStartDialogbox_Click() }
            // 
            // label2
            // 
            Self:label2:AutoSize := True
            Self:label2:Location := System.Drawing.Point{7, 34}
            Self:label2:Name := "label2"
            Self:label2:Size := System.Drawing.Size{80, 17}
            Self:label2:TabIndex := 0
            Self:label2:Text := "Username:"
            // 
            // lbUsername
            // 
            Self:lbUsername:AutoSize := True
            Self:lbUsername:BackColor := System.Drawing.Color.FromArgb(((Int)(((Byte)(255)))), ((Int)(((Byte)(224)))), ((Int)(((Byte)(192)))))
            Self:lbUsername:Location := System.Drawing.Point{119, 34}
            Self:lbUsername:Name := "lbUsername"
            Self:lbUsername:Size := System.Drawing.Size{80, 17}
            Self:lbUsername:TabIndex := 1
            Self:lbUsername:Text := "Username:"
            // 
            // lbBirthdate
            // 
            Self:lbBirthdate:AutoSize := True
            Self:lbBirthdate:BackColor := System.Drawing.Color.FromArgb(((Int)(((Byte)(255)))), ((Int)(((Byte)(224)))), ((Int)(((Byte)(192)))))
            Self:lbBirthdate:Location := System.Drawing.Point{119, 68}
            Self:lbBirthdate:Name := "lbBirthdate"
            Self:lbBirthdate:Size := System.Drawing.Size{66, 17}
            Self:lbBirthdate:TabIndex := 3
            Self:lbBirthdate:Text := "Birthdate"
            // 
            // label4
            // 
            Self:label4:AutoSize := True
            Self:label4:Location := System.Drawing.Point{7, 68}
            Self:label4:Name := "label4"
            Self:label4:Size := System.Drawing.Size{70, 17}
            Self:label4:TabIndex := 2
            Self:label4:Text := "Birthdate:"
            // 
            // MainForm
            // 
            Self:AutoScaleDimensions := System.Drawing.SizeF{8, 17}
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:ClientSize := System.Drawing.Size{634, 421}
            Self:Controls:Add(Self:bnStartDialogbox)
            Self:Controls:Add(Self:groupBox1)
            Self:Controls:Add(Self:label1)
            Self:Font := System.Drawing.Font{"Arial", 11.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((Byte)(0))}
            Self:Margin := System.Windows.Forms.Padding{5, 4, 5, 4}
            Self:Name := "MainForm"
            Self:Text := "Dialogbox Example"
            Self:groupBox1:ResumeLayout(False)
            Self:groupBox1:PerformLayout()
            Self:ResumeLayout(False)
        End Method
        #endregion
    End Class 
End Namespace
