//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.14.0.4
//     Timestamp      : 18.08.2023 14:24:21
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace DialogboxExample

    Public Partial Class DialogForm

        /// <summary>
        /// Required designer variable.
        /// </summary>
        Private components := Null As System.ComponentModel.IContainer
        Private tableLayoutPanel1 As System.Windows.Forms.TableLayoutPanel
        Private groupBox1 As System.Windows.Forms.GroupBox
        Private bnCancel As System.Windows.Forms.Button
        Private bnOK As System.Windows.Forms.Button
        Private panel1 As System.Windows.Forms.Panel
        Private label2 As System.Windows.Forms.Label
        Private tbUsername As System.Windows.Forms.TextBox
        Private label1 As System.Windows.Forms.Label
        Private mcBirthdate As System.Windows.Forms.MonthCalendar

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Override Method Dispose(disposing As Logic) As Void Strict

            If (disposing .and. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
			Return
        End Method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        Private Method InitializeComponent() As Void Strict
            Self:tableLayoutPanel1 := System.Windows.Forms.TableLayoutPanel{}
            Self:groupBox1 := System.Windows.Forms.GroupBox{}
            Self:bnCancel := System.Windows.Forms.Button{}
            Self:bnOK := System.Windows.Forms.Button{}
            Self:panel1 := System.Windows.Forms.Panel{}
            Self:label2 := System.Windows.Forms.Label{}
            Self:tbUsername := System.Windows.Forms.TextBox{}
            Self:label1 := System.Windows.Forms.Label{}
            Self:mcBirthdate := System.Windows.Forms.MonthCalendar{}
            Self:tableLayoutPanel1:SuspendLayout()
            Self:groupBox1:SuspendLayout()
            Self:panel1:SuspendLayout()
            Self:SuspendLayout()
            // 
            // tableLayoutPanel1
            // 
            Self:tableLayoutPanel1:ColumnCount := 2
            Self:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{System.Windows.Forms.SizeType.Percent, 20.1877937})
            Self:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{System.Windows.Forms.SizeType.Percent, 79.81221})
            Self:tableLayoutPanel1:Controls:Add(Self:groupBox1, 1, 1)
            Self:tableLayoutPanel1:Controls:Add(Self:panel1, 1, 0)
            Self:tableLayoutPanel1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:tableLayoutPanel1:Location := System.Drawing.Point{0, 0}
            Self:tableLayoutPanel1:Name := "tableLayoutPanel1"
            Self:tableLayoutPanel1:RowCount := 2
            Self:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 72.85319})
            Self:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 27.1468143})
            Self:tableLayoutPanel1:Size := System.Drawing.Size{426, 361}
            Self:tableLayoutPanel1:TabIndex := 0
            // 
            // groupBox1
            // 
            Self:groupBox1:Controls:Add(Self:bnCancel)
            Self:groupBox1:Controls:Add(Self:bnOK)
            Self:groupBox1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:groupBox1:Location := System.Drawing.Point{89, 266}
            Self:groupBox1:Name := "groupBox1"
            Self:groupBox1:Size := System.Drawing.Size{334, 92}
            Self:groupBox1:TabIndex := 0
            Self:groupBox1:TabStop := false
            // 
            // bnCancel
            // 
            Self:bnCancel:DialogResult := System.Windows.Forms.DialogResult.Cancel
            Self:bnCancel:Location := System.Drawing.Point{180, 25}
            Self:bnCancel:Name := "bnCancel"
            Self:bnCancel:Size := System.Drawing.Size{115, 37}
            Self:bnCancel:TabIndex := 1
            Self:bnCancel:Text := "&Cancel"
            Self:bnCancel:UseVisualStyleBackColor := true
            // 
            // bnOK
            // 
            Self:bnOK:Location := System.Drawing.Point{39, 25}
            Self:bnOK:Name := "bnOK"
            Self:bnOK:Size := System.Drawing.Size{115, 37}
            Self:bnOK:TabIndex := 0
            Self:bnOK:Text := "&OK"
            Self:bnOK:UseVisualStyleBackColor := true
            Self:bnOK:Click += System.EventHandler{ Self, @bnOK_Click() }
            // 
            // panel1
            // 
            Self:panel1:Controls:Add(Self:label2)
            Self:panel1:Controls:Add(Self:tbUsername)
            Self:panel1:Controls:Add(Self:label1)
            Self:panel1:Controls:Add(Self:mcBirthdate)
            Self:panel1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:panel1:Location := System.Drawing.Point{89, 3}
            Self:panel1:Name := "panel1"
            Self:panel1:Size := System.Drawing.Size{334, 257}
            Self:panel1:TabIndex := 1
            // 
            // label2
            // 
            Self:label2:AutoSize := true
            Self:label2:Location := System.Drawing.Point{16, 62}
            Self:label2:Name := "label2"
            Self:label2:Size := System.Drawing.Size{78, 18}
            Self:label2:TabIndex := 5
            Self:label2:Text := "Birthdate:"
            // 
            // tbUsername
            // 
            Self:tbUsername:Location := System.Drawing.Point{106, 27}
            Self:tbUsername:Name := "tbUsername"
            Self:tbUsername:Size := System.Drawing.Size{178, 25}
            Self:tbUsername:TabIndex := 4
            // 
            // label1
            // 
            Self:label1:AutoSize := true
            Self:label1:Location := System.Drawing.Point{16, 27}
            Self:label1:Name := "label1"
            Self:label1:Size := System.Drawing.Size{84, 18}
            Self:label1:TabIndex := 3
            Self:label1:Text := "Username:"
            // 
            // mcBirthdate
            // 
            Self:mcBirthdate:Location := System.Drawing.Point{106, 64}
            Self:mcBirthdate:Name := "mcBirthdate"
            Self:mcBirthdate:TabIndex := 2
            // 
            // DialogForm
            // 
            Self:AcceptButton := Self:bnOK
            Self:AutoScaleDimensions := System.Drawing.SizeF{9, 18}
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:CancelButton := Self:bnCancel
            Self:ClientSize := System.Drawing.Size{426, 361}
            Self:Controls:Add(Self:tableLayoutPanel1)
            Self:Font := System.Drawing.Font{"Arial", 11.25, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((Byte)(0))}
            Self:Margin := System.Windows.Forms.Padding{4}
            Self:Name := "DialogForm"
            Self:ShowInTaskbar := false
            Self:StartPosition := System.Windows.Forms.FormStartPosition.CenterParent
            Self:Text := "This is the dialog window"
            Self:tableLayoutPanel1:ResumeLayout(false)
            Self:groupBox1:ResumeLayout(false)
            Self:panel1:ResumeLayout(false)
            Self:panel1:PerformLayout()
            Self:ResumeLayout(false)
        End Method
        #endregion
    End Class 
End Namespace
