//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.14.0.4
//     Timestamp      : 19.08.2023 22:06:50
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace WindowsFormsApplication1

    Public Partial Class Form1

        /// <summary>
        /// Required designer variable.
        /// </summary>
        Private components := Null As System.ComponentModel.IContainer
        Private button1 As System.Windows.Forms.Button

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Override Method Dispose(disposing As Logic) As Void  Strict

            If (disposing .AND. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
			Return
        End Method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        Private Method InitializeComponent() As Void Strict
            Self:button1 := System.Windows.Forms.Button{}
            Self:SuspendLayout()
            // 
            // button1
            // 
            Self:button1:Location := System.Drawing.Point{34, 54}
            Self:button1:Name := "button1"
            Self:button1:Size := System.Drawing.Size{221, 96}
            Self:button1:TabIndex := 0
            Self:button1:Text := "button1"
            Self:button1:UseVisualStyleBackColor := true
            Self:button1:Click += System.EventHandler{ Self, @button1_Click() }
            // 
            // Form1
            // 
            Self:AutoScaleDimensions := System.Drawing.SizeF{9, 20}
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:ClientSize := System.Drawing.Size{278, 244}
            Self:Controls:Add(Self:button1)
            Self:Name := "Form1"
            Self:Text := "Form1"
            Self:ResumeLayout(false)
        End Method
        #endregion
    End Class 
End Namespace
