//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.14.0.4
//     Timestamp      : 19.08.2023 10:28:31
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace WebserviceExample

    Public Partial Class MainForm

        /// <summary>
        /// Required designer variable.
        /// </summary>
        Private components := Null As System.ComponentModel.IContainer
        Private tableLayoutPanel1 As System.Windows.Forms.TableLayoutPanel
        Private panel1 As System.Windows.Forms.Panel
        Private lbStatus As System.Windows.Forms.ListBox
        Private dvData As System.Windows.Forms.DataGridView
        Private bnGetDataTyped As System.Windows.Forms.Button
        Private bnGetDataUntyped As System.Windows.Forms.Button

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Override Method Dispose(disposing As Logic) As Void  Strict

            If (disposing .AND. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
			Return
        End Method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        Private Method InitializeComponent() As Void Strict
            Self:tableLayoutPanel1 := System.Windows.Forms.TableLayoutPanel{}
            Self:panel1 := System.Windows.Forms.Panel{}
            Self:bnGetDataTyped := System.Windows.Forms.Button{}
            Self:bnGetDataUntyped := System.Windows.Forms.Button{}
            Self:lbStatus := System.Windows.Forms.ListBox{}
            Self:dvData := System.Windows.Forms.DataGridView{}
            Self:tableLayoutPanel1:SuspendLayout()
            Self:panel1:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(Self:dvData)):BeginInit()
            Self:SuspendLayout()
            // 
            // tableLayoutPanel1
            // 
            Self:tableLayoutPanel1:ColumnCount := 1
            Self:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{System.Windows.Forms.SizeType.Percent, 100})
            Self:tableLayoutPanel1:Controls:Add(Self:panel1, 0, 0)
            Self:tableLayoutPanel1:Controls:Add(Self:lbStatus, 0, 2)
            Self:tableLayoutPanel1:Controls:Add(Self:dvData, 0, 1)
            Self:tableLayoutPanel1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:tableLayoutPanel1:Location := System.Drawing.Point{0, 0}
            Self:tableLayoutPanel1:Name := "tableLayoutPanel1"
            Self:tableLayoutPanel1:RowCount := 3
            Self:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 25.7383957})
            Self:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 74.2616043})
            Self:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Absolute, 123})
            Self:tableLayoutPanel1:Size := System.Drawing.Size{1031, 504}
            Self:tableLayoutPanel1:TabIndex := 0
            // 
            // panel1
            // 
            Self:panel1:Controls:Add(Self:bnGetDataTyped)
            Self:panel1:Controls:Add(Self:bnGetDataUntyped)
            Self:panel1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:panel1:Location := System.Drawing.Point{3, 3}
            Self:panel1:Name := "panel1"
            Self:panel1:Size := System.Drawing.Size{1025, 92}
            Self:panel1:TabIndex := 0
            // 
            // bnGetDataTyped
            // 
            Self:bnGetDataTyped:BackColor := System.Drawing.Color.FromArgb(((Int)(((Byte)(192)))), ((Int)(((Byte)(255)))), ((Int)(((Byte)(192)))))
            Self:bnGetDataTyped:Location := System.Drawing.Point{650, 17}
            Self:bnGetDataTyped:Name := "bnGetDataTyped"
            Self:bnGetDataTyped:Size := System.Drawing.Size{225, 60}
            Self:bnGetDataTyped:TabIndex := 1
            Self:bnGetDataTyped:Text := "Get Data (typed)"
            Self:bnGetDataTyped:UseVisualStyleBackColor := False
            Self:bnGetDataTyped:Click += System.EventHandler{ Self, @bnGetDataTyped_Click() }
            // 
            // bnGetDataUntyped
            // 
            Self:bnGetDataUntyped:BackColor := System.Drawing.Color.FromArgb(((Int)(((Byte)(255)))), ((Int)(((Byte)(255)))), ((Int)(((Byte)(192)))))
            Self:bnGetDataUntyped:Location := System.Drawing.Point{185, 17}
            Self:bnGetDataUntyped:Name := "bnGetDataUntyped"
            Self:bnGetDataUntyped:Size := System.Drawing.Size{225, 60}
            Self:bnGetDataUntyped:TabIndex := 0
            Self:bnGetDataUntyped:Text := "Get Data (untyped)"
            Self:bnGetDataUntyped:UseVisualStyleBackColor := False
            Self:bnGetDataUntyped:Click += System.EventHandler{ Self, @bnGetDataUntyped_Click() }
            // 
            // lbStatus
            // 
            Self:lbStatus:BackColor := System.Drawing.Color.FromArgb(((Int)(((Byte)(255)))), ((Int)(((Byte)(224)))), ((Int)(((Byte)(192)))))
            Self:lbStatus:Dock := System.Windows.Forms.DockStyle.Fill
            Self:lbStatus:FormattingEnabled := true
            Self:lbStatus:ItemHeight := 18
            Self:lbStatus:Location := System.Drawing.Point{3, 383}
            Self:lbStatus:Name := "lbStatus"
            Self:lbStatus:Size := System.Drawing.Size{1025, 118}
            Self:lbStatus:TabIndex := 1
            // 
            // dvData
            // 
            Self:dvData:ColumnHeadersHeightSizeMode := System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Self:dvData:Dock := System.Windows.Forms.DockStyle.Fill
            Self:dvData:Location := System.Drawing.Point{3, 101}
            Self:dvData:Name := "dvData"
            Self:dvData:Size := System.Drawing.Size{1025, 276}
            Self:dvData:TabIndex := 2
            // 
            // MainForm
            // 
            Self:AutoScaleDimensions := System.Drawing.SizeF{9, 18}
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:ClientSize := System.Drawing.Size{1031, 504}
            Self:Controls:Add(Self:tableLayoutPanel1)
            Self:Font := System.Drawing.Font{"Arial", 11.25, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((Byte)(0))}
            Self:Margin := System.Windows.Forms.Padding{4}
            Self:Name := "MainForm"
            Self:Text := "Calling a Webservice from an X# applicatiion"
            Self:tableLayoutPanel1:ResumeLayout(false)
            Self:panel1:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(Self:dvData)):EndInit()
            Self:ResumeLayout(false)
        End Method
        #endregion
    End Class 
End Namespace
