//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.13.2.2
//     Timestamp      : 01.05.2023 20:45:41
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace WinFormsDataBinding_16

    Public Partial Class MainForm

        /// <summary>
        /// Required designer variable.
        /// </summary>
        Private components := Null As System.ComponentModel.IContainer
        Private tableLayoutPanel1 As System.Windows.Forms.TableLayoutPanel
        Private groupBox1 As System.Windows.Forms.GroupBox
        Private bnMoveLast As System.Windows.Forms.Button
        Private bnMoveNext As System.Windows.Forms.Button
        Private bnMovePrev As System.Windows.Forms.Button
        Private bnMoveFirst As System.Windows.Forms.Button
        Private dataGridView1 As System.Windows.Forms.DataGridView

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        Protected Override Method Dispose(disposing As Logic) As Void  Strict

            If (disposing .AND. (components != null))
                components:Dispose()
            Endif
            Super:Dispose(disposing)
			Return
        End Method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        Private Method InitializeComponent() As Void Strict
            Self:tableLayoutPanel1 := System.Windows.Forms.TableLayoutPanel{}
            Self:dataGridView1 := System.Windows.Forms.DataGridView{}
            Self:groupBox1 := System.Windows.Forms.GroupBox{}
            Self:bnMoveLast := System.Windows.Forms.Button{}
            Self:bnMoveNext := System.Windows.Forms.Button{}
            Self:bnMovePrev := System.Windows.Forms.Button{}
            Self:bnMoveFirst := System.Windows.Forms.Button{}
            Self:tableLayoutPanel1:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(Self:dataGridView1)):BeginInit()
            Self:groupBox1:SuspendLayout()
            Self:SuspendLayout()
            // 
            // tableLayoutPanel1
            // 
            Self:tableLayoutPanel1:ColumnCount := 1
            Self:tableLayoutPanel1:ColumnStyles:Add(System.Windows.Forms.ColumnStyle{System.Windows.Forms.SizeType.Percent, 100})
            Self:tableLayoutPanel1:Controls:Add(Self:groupBox1, 0, 1)
            Self:tableLayoutPanel1:Controls:Add(Self:dataGridView1, 0, 0)
            Self:tableLayoutPanel1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:tableLayoutPanel1:Location := System.Drawing.Point{0, 0}
            Self:tableLayoutPanel1:Name := "tableLayoutPanel1"
            Self:tableLayoutPanel1:RowCount := 2
            Self:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 75})
            Self:tableLayoutPanel1:RowStyles:Add(System.Windows.Forms.RowStyle{System.Windows.Forms.SizeType.Percent, 25})
            Self:tableLayoutPanel1:Size := System.Drawing.Size{772, 595}
            Self:tableLayoutPanel1:TabIndex := 2
            // 
            // dataGridView1
            // 
            Self:dataGridView1:ColumnHeadersHeightSizeMode := System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
            Self:dataGridView1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:dataGridView1:Location := System.Drawing.Point{3, 3}
            Self:dataGridView1:Name := "dataGridView1"
            Self:dataGridView1:RowHeadersWidth := 62
            Self:dataGridView1:RowTemplate:Height := 28
            Self:dataGridView1:Size := System.Drawing.Size{766, 440}
            Self:dataGridView1:TabIndex := 1
            // 
            // groupBox1
            // 
            Self:groupBox1:Controls:Add(Self:bnMoveLast)
            Self:groupBox1:Controls:Add(Self:bnMoveNext)
            Self:groupBox1:Controls:Add(Self:bnMovePrev)
            Self:groupBox1:Controls:Add(Self:bnMoveFirst)
            Self:groupBox1:Dock := System.Windows.Forms.DockStyle.Fill
            Self:groupBox1:Location := System.Drawing.Point{3, 449}
            Self:groupBox1:Name := "groupBox1"
            Self:groupBox1:Size := System.Drawing.Size{766, 143}
            Self:groupBox1:TabIndex := 2
            Self:groupBox1:TabStop := false
            Self:groupBox1:Text := "DataControl"
            // 
            // bnMoveLast
            // 
            Self:bnMoveLast:Location := System.Drawing.Point{346, 45}
            Self:bnMoveLast:Name := "bnMoveLast"
            Self:bnMoveLast:Size := System.Drawing.Size{75, 49}
            Self:bnMoveLast:TabIndex := 3
            Self:bnMoveLast:Text := ">|"
            Self:bnMoveLast:UseVisualStyleBackColor := true
            // 
            // bnMoveNext
            // 
            Self:bnMoveNext:Location := System.Drawing.Point{239, 45}
            Self:bnMoveNext:Name := "bnMoveNext"
            Self:bnMoveNext:Size := System.Drawing.Size{75, 49}
            Self:bnMoveNext:TabIndex := 2
            Self:bnMoveNext:Text := ">"
            Self:bnMoveNext:UseVisualStyleBackColor := true
            // 
            // bnMovePrev
            // 
            Self:bnMovePrev:Location := System.Drawing.Point{139, 45}
            Self:bnMovePrev:Name := "bnMovePrev"
            Self:bnMovePrev:Size := System.Drawing.Size{75, 49}
            Self:bnMovePrev:TabIndex := 1
            Self:bnMovePrev:Text := "<"
            Self:bnMovePrev:UseVisualStyleBackColor := true
            // 
            // bnMoveFirst
            // 
            Self:bnMoveFirst:Location := System.Drawing.Point{32, 45}
            Self:bnMoveFirst:Name := "bnMoveFirst"
            Self:bnMoveFirst:Size := System.Drawing.Size{75, 49}
            Self:bnMoveFirst:TabIndex := 0
            Self:bnMoveFirst:Text := "|<"
            Self:bnMoveFirst:UseVisualStyleBackColor := true
            // 
            // MainForm
            // 
            Self:AutoScaleDimensions := System.Drawing.SizeF{11, 26}
            Self:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            Self:ClientSize := System.Drawing.Size{772, 595}
            Self:Controls:Add(Self:tableLayoutPanel1)
            Self:Font := System.Drawing.Font{"Arial Narrow", 11, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((Byte)(0))}
            Self:Margin := System.Windows.Forms.Padding{4}
            Self:Name := "MainForm"
            Self:Text := "Simple DataBinding with BindingSource"
            Self:tableLayoutPanel1:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(Self:dataGridView1)):EndInit()
            Self:groupBox1:ResumeLayout(false)
            Self:ResumeLayout(false)
        End Method
        #endregion
    End Class 
End Namespace
