//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.13.2.2
//     Timestamp      : 05.04.2023 07:42:19
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
BEGIN NAMESPACE BackgroundWorker_Example

    PUBLIC PARTIAL CLASS MainForm

        /// <summary>
        /// Required designer variable.
        /// </summary>
        private components := NULL AS System.ComponentModel.IContainer
        Internal liFiles AS System.Windows.Forms.ListBox
        PRIVATE tbPath AS System.Windows.Forms.TextBox
        PRIVATE label1 AS System.Windows.Forms.Label
        PRIVATE cbBackgroundWorker AS System.Windows.Forms.CheckBox
        Internal progressBar1 AS System.Windows.Forms.ProgressBar
        PRIVATE groupBox1 AS System.Windows.Forms.GroupBox
        PRIVATE bnCancel AS System.Windows.Forms.Button
        PRIVATE bnStart AS System.Windows.Forms.Button
        Internal pictureBox1 AS System.Windows.Forms.PictureBox
 
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override method Dispose(disposing as logic) as void  STRICT

            if (disposing .AND. (components != null))
                components:Dispose()
            endif
            Super:Dispose(disposing)
			return
        end method
        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private METHOD InitializeComponent() AS VOID STRICT
            SELF:cbBackgroundWorker := System.Windows.Forms.CheckBox{}
            SELF:liFiles := System.Windows.Forms.ListBox{}
            SELF:tbPath := System.Windows.Forms.TextBox{}
            SELF:label1 := System.Windows.Forms.Label{}
            SELF:progressBar1 := System.Windows.Forms.ProgressBar{}
            SELF:groupBox1 := System.Windows.Forms.GroupBox{}
            SELF:bnCancel := System.Windows.Forms.Button{}
            SELF:bnStart := System.Windows.Forms.Button{}
            SELF:pictureBox1 := System.Windows.Forms.PictureBox{}
            SELF:groupBox1:SuspendLayout()
            ((System.ComponentModel.ISupportInitialize)(SELF:pictureBox1)):BeginInit()
            SELF:SuspendLayout()
            // 
            // cbBackgroundWorker
            // 
            SELF:cbBackgroundWorker:AutoSize := true
            SELF:cbBackgroundWorker:Location := System.Drawing.Point{160, 141}
            SELF:cbBackgroundWorker:Name := "cbBackgroundWorker"
            SELF:cbBackgroundWorker:Size := System.Drawing.Size{154, 24}
            SELF:cbBackgroundWorker:TabIndex := 1
            SELF:cbBackgroundWorker:Text := "Mit BackgroundWorker"
            SELF:cbBackgroundWorker:UseVisualStyleBackColor := true
            // 
            // liFiles
            // 
            SELF:liFiles:FormattingEnabled := true
            SELF:liFiles:ItemHeight := 20
            SELF:liFiles:Location := System.Drawing.Point{53, 216}
            SELF:liFiles:Name := "liFiles"
            SELF:liFiles:Size := System.Drawing.Size{435, 164}
            SELF:liFiles:TabIndex := 2
            // 
            // tbPath
            // 
            SELF:tbPath:Location := System.Drawing.Point{53, 38}
            SELF:tbPath:Name := "tbPath"
            SELF:tbPath:Size := System.Drawing.Size{435, 25}
            SELF:tbPath:TabIndex := 3
            // 
            // label1
            // 
            SELF:label1:AutoSize := true
            SELF:label1:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(192)))), ((INT)(((BYTE)(255)))), ((INT)(((BYTE)(192)))))
            SELF:label1:Location := System.Drawing.Point{53, 15}
            SELF:label1:Name := "label1"
            SELF:label1:Size := System.Drawing.Size{37, 20}
            SELF:label1:TabIndex := 4
            SELF:label1:Text := "Pfad:"
            // 
            // progressBar1
            // 
            SELF:progressBar1:Location := System.Drawing.Point{53, 187}
            SELF:progressBar1:Name := "progressBar1"
            SELF:progressBar1:Size := System.Drawing.Size{435, 23}
            SELF:progressBar1:Step := 1
            SELF:progressBar1:TabIndex := 5
            // 
            // groupBox1
            // 
            SELF:groupBox1:Controls:Add(SELF:bnCancel)
            SELF:groupBox1:Controls:Add(SELF:bnStart)
            SELF:groupBox1:Location := System.Drawing.Point{57, 80}
            SELF:groupBox1:Name := "groupBox1"
            SELF:groupBox1:Size := System.Drawing.Size{431, 55}
            SELF:groupBox1:TabIndex := 6
            SELF:groupBox1:TabStop := false
            SELF:groupBox1:Text := "Start/Cancel"
            // 
            // bnCancel
            // 
            SELF:bnCancel:Location := System.Drawing.Point{248, 17}
            SELF:bnCancel:Name := "bnCancel"
            SELF:bnCancel:Size := System.Drawing.Size{128, 32}
            SELF:bnCancel:TabIndex := 2
            SELF:bnCancel:Text := "&Cancel"
            SELF:bnCancel:UseVisualStyleBackColor := true
            SELF:bnCancel:Click += System.EventHandler{ SELF, @bnCancel_Click() }
            // 
            // bnStart
            // 
            SELF:bnStart:Location := System.Drawing.Point{103, 17}
            SELF:bnStart:Name := "bnStart"
            SELF:bnStart:Size := System.Drawing.Size{128, 32}
            SELF:bnStart:TabIndex := 1
            SELF:bnStart:Text := "&Start"
            SELF:bnStart:UseVisualStyleBackColor := true
            SELF:bnStart:Click += System.EventHandler{ SELF, @bnStart_Click() }
            // 
            // pictureBox1
            // 
            SELF:pictureBox1:BackColor := System.Drawing.Color.FromArgb(((INT)(((BYTE)(255)))), ((INT)(((BYTE)(224)))), ((INT)(((BYTE)(192)))))
            SELF:pictureBox1:BorderStyle := System.Windows.Forms.BorderStyle.FixedSingle
            SELF:pictureBox1:Location := System.Drawing.Point{53, 386}
            SELF:pictureBox1:Name := "pictureBox1"
            SELF:pictureBox1:Size := System.Drawing.Size{125, 102}
            SELF:pictureBox1:SizeMode := System.Windows.Forms.PictureBoxSizeMode.StretchImage
            SELF:pictureBox1:TabIndex := 7
            SELF:pictureBox1:TabStop := false
            // 
            // MainForm
            // 
            SELF:AutoScaleDimensions := System.Drawing.SizeF{7, 20}
            SELF:AutoScaleMode := System.Windows.Forms.AutoScaleMode.Font
            SELF:ClientSize := System.Drawing.Size{511, 494}
            SELF:Controls:Add(SELF:pictureBox1)
            SELF:Controls:Add(SELF:groupBox1)
            SELF:Controls:Add(SELF:progressBar1)
            SELF:Controls:Add(SELF:label1)
            SELF:Controls:Add(SELF:tbPath)
            SELF:Controls:Add(SELF:liFiles)
            SELF:Controls:Add(SELF:cbBackgroundWorker)
            SELF:Font := System.Drawing.Font{"Arial Narrow", 11.25, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((BYTE)(0))}
            SELF:Margin := System.Windows.Forms.Padding{4, 5, 4, 5}
            SELF:Name := "MainForm"
            SELF:Text := "Example for BackgroundWorker class"
            SELF:groupBox1:ResumeLayout(false)
            ((System.ComponentModel.ISupportInitialize)(SELF:pictureBox1)):EndInit()
            SELF:ResumeLayout(false)
            SELF:PerformLayout()
        END METHOD
        #endregion
    END CLASS 
END NAMESPACE
