//------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime version: 4.0.30319.42000
//     Generator      : XSharp.CodeDomProvider 2.14.0.4
//     Timestamp      : 20.08.2023 15:10:46
//     
//     Changes to this file may cause incorrect behavior and may be lost if
//     the code is regenerated.
//  </auto-generated>
//------------------------------------------------------------------------------
Begin Namespace SettingsExample.Properties
    Using System
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")] ;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()] ;
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()] ;
    Public Class Resources
        Private Static resourceMan As global::System.Resources.ResourceManager
        Private Static resourceCulture As global::System.Globalization.CultureInfo
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")] ;
                Internal Constructor() Strict
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
                Internal Static Property ResourceManager As global::System.Resources.ResourceManager
        
            Get
                If System.Object.ReferenceEquals(resourceMan, Null)
                    Local temp := global::System.Resources.ResourceManager{"SettingsExample.Properties.Resources", typeof(Resources):Assembly} As global::System.Resources.ResourceManager
                    resourceMan := temp
                Endif
                Return resourceMan
            End Get
        End Property 
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)] ;
                Internal Static Property Culture As global::System.Globalization.CultureInfo
        
            Get
                Return resourceCulture
            End Get
        
            Set
                resourceCulture := value
            End Set
        End Property 
    
    End Class 
End Namespace
